### ISSUE TITLE
OverflowException: TimeSpan overflowed because the duration is too long in StrategyVM

### ISSUE THREAD

**Issue by Discostoff** [DrVinnEck/ACC-DRIVE-issues#80]
Runtime Error Date: 11/11/2022 22:09:12 
 Runtime Error: Application: ACC DRIVE.exe
CoreCLR Version: 6.0.1122.52304
.NET Version: 6.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException: TimeSpan overflowed because the duration is too long.
at System.TimeSpan.IntervalFromDoubleTicks(Double ticks)
at ACC_DRIVE.ViewModel.BonoAtHome.StrategyVM.UpdateUi()
at ACC_DRIVE.ViewModel.BonoAtHome.StrategyVM.Update(System.Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
at System.Threading.TimerQueue.FireNextTimers()

**Comment by rrennoir** [comment]
Telemetry times can be bigger than long.MaxValues ? 🤨
